### ISSUE TITLE
Defaulting to user installation because normal site-packages is not writeable

### ISSUE THREAD

**Issue by godson14** [scikit-learn/blog#164]
Defaulting to user installation because normal site-packages is not writeable
Collecting pygtk
  Using cached pygtk-2.24.0.tar.bz2 (2.4 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      ERROR: Could not import dsextras module: Make sure you have installed pygobject.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

someone please find solution to the above problem

_Originally posted by @godson14 in https://github.com/scikit-learn/scikit-learn/issues/14729#issuecomment-1585722943_

**Comment by reshamas** [comment]
@godson14 
This repo is for the scikit-learn blog, it is not for the code development.

For questions on usage, or bugs, this may be what you are looking for:
https://scikit-learn.org/stable/support.html

To report a bug, here are the instructions:  
https://scikit-learn.org/stable/support.html#bug-tracker

In the meantime, closing this issue here.
