### ISSUE TITLE
 set up CNAME file to point to blog.scikit-learn.org

### ISSUE THREAD

**Issue by reshamas** [scikit-learn/blog#23]

**Comment by GaelVaroquaux** [comment]
Action must be taken on the DNS side for this to work.

I'm pretty bad with DNS, I must admit. @ogrisel is much better than I am.

**Comment by ogrisel** [comment]
I will have a look.

**Comment by ogrisel** [comment]
After a few mistakes I have configured the DNS by adding the following record:

```
blog.scikit-learn.org.	83	IN	CNAME	scikit-learn.org.
```

which leads to the currently active configuration:

```
$ dig blog.scikit-learn.org +nostats +nocomments +nocmd

; <<>> DiG 9.10.6 <<>> blog.scikit-learn.org +nostats +nocomments +nocmd
;; global options: +cmd
;blog.scikit-learn.org.		IN	A
blog.scikit-learn.org.	300	IN	CNAME	scikit-learn.org.
scikit-learn.org.	1047	IN	A	185.199.110.153
scikit-learn.org.	1047	IN	A	185.199.108.153
scikit-learn.org.	1047	IN	A	185.199.109.153
scikit-learn.org.	1047	IN	A	185.199.111.153
```

then I tried to configure the new custom domain name on github's side in https://github.com/scikit-learn/blog/settings/pages, as follows:

![image](https://user-images.githubusercontent.com/89061/151344400-79c22880-2497-4111-9b6b-24a406e5383a.png)

It is now possible to go to https://blog.scikit-learn.org/ but the rendering is broken because links to CSS and JS needs to be updated as seen in the firefox console (there is an extra `/blog/` segment in the the URL):

![image](https://user-images.githubusercontent.com/89061/151344960-15015381-aef9-453e-8167-8a5ae1ec0ad5.png)

Maybe it would be possible to use relative links instead of absolute links for those resources to get them working under both base URLs:

- https://blog.scikit-learn.org/
- https://scikit-learn.org/blog/

For the record here is the full DNS config:

```
@ 10800 IN SOA ns1.gandi.net. hostmaster.gandi.net. 1643280421 10800 3600 604800 10800
@ 7200 IN A 185.199.108.153
@ 7200 IN A 185.199.109.153
@ 7200 IN A 185.199.110.153
@ 7200 IN A 185.199.111.153
@ 10800 IN MX 10 spool.mail.gandi.net.
@ 10800 IN MX 50 fb.mail.gandi.net.
@ 10800 IN TXT "v=spf1 include:_mailcust.gandi.net ?all"
blog 300 IN CNAME scikit-learn.org.
contrib 7200 IN CNAME scikit-learn-contrib.github.io.
www 10800 IN CNAME webredir.gandi.net.
```

I might increase the TTL for the blog.scikit-learn.org record after a while.

**Comment by GaelVaroquaux** [comment]
Things now all work well. Fantastic! And thanks a lot!!

**Comment by reshamas** [comment]
@ogrisel Thank you!!!  

>Maybe it would be possible to use relative links instead of absolute links for those resources to get them working under both base URLs.

Yes, it's good practice for us to use relative links.

>~~But that will break browsing from https://scikit-learn.org/blog/ (but maybe we don't care?)~~

Internal Note:  Both these URLs work now:  
- https://scikit-learn.org/blog/
- https://blog.scikit-learn.org

@laurburke *Now* the blog is officially ready to be announced.

**Comment by reshamas** [comment]
@laurburke Does this URL update impact Google Analytics?

**Comment by laurburke** [comment]
@reshamas Since https://scikit-learn.org/blog/ now redirects to https://blog.scikit-learn.org, can change the GA baseurl to https://blog.scikit-learn.org. It may take a few days to update, but it should pick up all the traffic.

**Comment by laurburke** [comment]
@reshamas I have updated GA, we should wait a day to make sure it syncs correctly but we should be good.

**Comment by GaelVaroquaux** [comment]
I think that this can be closed. No?
