### ISSUE TITLE
BUG: calendar page, monthly meeting is now on MONDAY not FRIDAY

### ISSUE THREAD

**Issue by noatamir** [scikit-learn/blog#94]
the markdown says `Monthly meetings on the last Friday of the month`
If I'm not mistaken, the calendar shows that the meetings are now on the first Monday of the month.
correct to: `Monthly meetings on the first Monday of the month`

on file [calendar/](https://github.com/scikit-learn/blog/blob/main/_pages/calendar.md)

**Comment by reshamas** [comment]
@noatamir 
The monthly meetings are typically on the last Friday of the month.
(In the case of Dec 2020, (or other holidays),it was moved to early January.)

The last meeting was on March 28, 2022.

@thomasjpfan Is this still the case?

**Comment by thomasjpfan** [comment]
The monthly meeting is still the last Monday of each month. The last 6 meetings has been on the last Monday accept for December:

- March 28, 2022
- February 28, 2022
- January 31, 2022
- January 3, 2022 (Moved from December due to holidays)
- November 29, 2021
- October 25, 2021

The [UX in the public calendar](https://calendar.google.com/calendar/u/0/embed?src=social.scikitlearn@gmail.com&ctz=UTC) does sometimes place the last Monday of previous month at the top of the current month.

**Comment by reshamas** [comment]
@thomasjpfan I meant "Monday" (instead of Friday) !!!

It's been a really busy week, and I wish it was Friday already :)
